FROM schoolofdevops/maven:spring AS build
WORKDIR /app
COPY . .
RUN mvn package





FROM openjdk:8-alpine AS run
COPY --from=build /app/target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar /run/petclinic.jar
EXPOSE 8080
CMD java -jar /run/petclinic.jar
