app:
  image: rustam11987/petclinic:v6
  ports:
    - 8080:8080
  environment:
    - spring.profiles.active=mysql
  links:
    - db:db
db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
